restaurants = [
    {"name": "zen cafe", "weight": 100, "tags": ["brunch"]},
    {"name": "poke guy", "weight": 100, "tags": ["poke", "asian"]},
    {"name": "gyukaku", "weight": 100, "tags": ["bbq", "meat"]},
    {"name": "nook", "weight": 100, "tags": ["italian"]},
    {"name": "thai away", "weight": 100, "tags": ["thai", "asian"]},
    {"name": "jinya", "weight": 100, "tags": ["ramen", "asian"]},
    {"name": "itto", "weight": 100, "tags": ["ramen", "asian"]},
    {"name": "old spaghetti factory", "weight": 100, "tags": ["italian", "chain"]},
    {"name": "indian oven", "weight": 100, "tags": ["indian", "asian"]},
    {"name": "five guys", "weight": 100, "tags": ["burgers", "meat"]},
    {"name": "east is east", "weight": 100, "tags": ["afghan", "asian"]},
    {"name": "hongdae pocha", "weight": 100, "tags": ["korean", "asian"]},
    {"name": "chosun", "weight": 100, "tags": ["korean", "asian"]},
    {"name": "delara", "weight": 100, "tags": ["persian", "middle east"]},
    {"name": "thai basil", "weight": 100, "tags": ["thai", "asian"]},
    {"name": "tera v burger", "weight": 100, "tags": ["burger", "vegetarian"]},
    {"name": "white spot", "weight": 100, "tags": ["burger", "vegetarian", "chain"]},
    {"name": "the kitchen dada", "weight": 100, "tags": ["sushi", "asian"]},
    {"name": "pokerrito", "weight": 100, "tags": ["poke", "asian"]},
    {"name": "pokey okey", "weight": 100, "tags": ["poke", "asian"]},
    {"name": "pacific poke", "weight": 100, "tags": ["poke", "asian"]},
    {"name": "uncle fatih's", "weight": 100, "tags": ["pizza", "italian", "chain"]},
    {"name": "reggiano pizza", "weight": 100, "tags": ["pizza", "italian"]},
    {"name": "spicy 6", "weight": 100, "tags": ["indian", "asian"]},
    {"name": "kosoo", "weight": 100, "tags": ["korean", "asian"]},
    {"name": "momo sushi robson", "weight": 100, "tags": ["sushi", "asian"]},
    {"name": "madani's kitchen", "weight": 100, "tags": ["mafe", "african"]},
]
